#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ORDERFLOW_ROOT="${ORDERFLOW_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
DEERFLOW_ROOT="${DEERFLOW_ROOT:-$(cd "$ORDERFLOW_ROOT/.." && pwd)/deer-flow}"
UPDATE_SKILL="${UPDATE_SKILL:-0}"

printf 'Order-flow repo: %s\n' "$ORDERFLOW_ROOT"
printf 'DeerFlow repo:   %s\n' "$DEERFLOW_ROOT"

[[ -f "$ORDERFLOW_ROOT/pyproject.toml" ]] || {
  echo "Order-flow repository root is invalid: $ORDERFLOW_ROOT" >&2
  exit 1
}

if [[ ! -d "$DEERFLOW_ROOT" ]]; then
  echo "Cloning DeerFlow..."
  git clone https://github.com/bytedance/deer-flow.git "$DEERFLOW_ROOT"
fi

for required in Makefile backend frontend config.example.yaml; do
  [[ -e "$DEERFLOW_ROOT/$required" ]] || {
    echo "DeerFlow root validation failed: missing $required" >&2
    exit 1
  }
done

command -v make >/dev/null 2>&1 || {
  echo "The 'make' command is required by DeerFlow's official bootstrap. Install/enable Make, then re-run this script." >&2
  exit 1
}

cd "$DEERFLOW_ROOT"

if [[ ! -f config.yaml ]]; then
  echo "Creating config.yaml with DeerFlow's repository command..."
  make config
else
  echo "config.yaml already exists; leaving existing values unchanged."
fi

if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  echo "Docker daemon detected. Preparing DeerFlow Docker prerequisites..."
  make docker-init
  SETUP_PATH="Docker"
  NEXT_COMMAND="make docker-start"
else
  echo "Docker daemon unavailable. Checking local DeerFlow prerequisites..."
  make check
  make install
  SETUP_PATH="Local"
  NEXT_COMMAND="make dev"
fi

SKILL_SOURCE="$ORDERFLOW_ROOT/integrations/deerflow/skills/custom/orderflow-research"
SKILL_TARGET="$DEERFLOW_ROOT/skills/custom/orderflow-research"
[[ -d "$SKILL_SOURCE" ]] || {
  echo "Migration skill source is missing: $SKILL_SOURCE" >&2
  exit 1
}

mkdir -p "$(dirname "$SKILL_TARGET")"
if [[ -d "$SKILL_TARGET" ]]; then
  if [[ "$UPDATE_SKILL" == "1" ]]; then
    echo "Updating existing orderflow-research DeerFlow skill..."
    rm -rf "$SKILL_TARGET"
    cp -R "$SKILL_SOURCE" "$SKILL_TARGET"
  else
    echo "orderflow-research skill already exists; preserving it. Set UPDATE_SKILL=1 to replace it from the repo template."
  fi
else
  cp -R "$SKILL_SOURCE" "$SKILL_TARGET"
fi

COMMIT="unknown"
if command -v git >/dev/null 2>&1; then
  COMMIT="$(git -C "$ORDERFLOW_ROOT" rev-parse HEAD 2>/dev/null || printf 'unknown')"
fi
mkdir -p "$SKILL_TARGET/references"
cat > "$SKILL_TARGET/references/local-project.md" <<EOF
# Generated local project binding

This file is generated by \`integrations/deerflow/bootstrap.sh\` and may be replaced on the next bootstrap.

- orderflow_project_root: \`$ORDERFLOW_ROOT\`
- deerflow_project_root: \`$DEERFLOW_ROOT\`
- orderflow_git_commit: \`$COMMIT\`
- generated_at_utc: \`$(date -u +%Y-%m-%dT%H:%M:%SZ)\`

Use \`orderflow_project_root\` as the canonical working directory for trading-project commands.
EOF

ENV_NAMES="$(grep -oE '\$[A-Z][A-Z0-9_]*' config.yaml | sed 's/^\$//' | sort -u | paste -sd ',' - || true)"
MODEL_CONFIGURED=0
python3 - <<'PY' && MODEL_CONFIGURED=1 || true
from pathlib import Path
lines = Path("config.yaml").read_text(encoding="utf-8").splitlines()
try:
    start = next(i for i, line in enumerate(lines) if line.strip() == "models:" and not line.startswith(" "))
except StopIteration:
    raise SystemExit(1)
for line in lines[start + 1:]:
    if line and not line.startswith((" ", "#")) and ":" in line:
        break
    if line.startswith("  - name:") and line.split(":", 1)[1].strip():
        raise SystemExit(0)
raise SystemExit(1)
PY

echo
echo "DeerFlow bootstrap complete."
echo "Setup path: $SETUP_PATH"
echo "config.yaml: present"
echo "orderflow-research skill: $SKILL_TARGET"
if [[ "$MODEL_CONFIGURED" != "1" ]]; then
  echo "WARNING: no active model entry was detected under models: in config.yaml. Add at least one model before launch." >&2
fi
if [[ -n "$ENV_NAMES" ]]; then
  printf 'Environment variable names referenced by config.yaml: %s\n' "$ENV_NAMES"
  echo "Values were not inspected."
fi
echo "Exact next command to launch DeerFlow:"
printf '  cd %q\n' "$DEERFLOW_ROOT"
printf '  %s\n' "$NEXT_COMMAND"
