param(
    [string]$DeerFlowRoot = "",
    [string]$OrderflowRoot = "",
    [switch]$UpdateSkill
)

$ErrorActionPreference = "Stop"

function Resolve-FullPath([string]$Path) {
    return [System.IO.Path]::GetFullPath((Join-Path (Get-Location) $Path))
}

$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not $OrderflowRoot) {
    $OrderflowRoot = [System.IO.Path]::GetFullPath((Join-Path $ScriptRoot "..\.."))
} else {
    $OrderflowRoot = Resolve-FullPath $OrderflowRoot
}
if (-not $DeerFlowRoot) {
    $DeerFlowRoot = [System.IO.Path]::GetFullPath((Join-Path $OrderflowRoot "..\deer-flow"))
} else {
    $DeerFlowRoot = Resolve-FullPath $DeerFlowRoot
}

Write-Host "Order-flow repo: $OrderflowRoot"
Write-Host "DeerFlow repo:   $DeerFlowRoot"

if (-not (Test-Path (Join-Path $OrderflowRoot "pyproject.toml"))) {
    throw "Order-flow repository root is invalid: $OrderflowRoot"
}

if (-not (Test-Path $DeerFlowRoot)) {
    Write-Host "Cloning DeerFlow..."
    git clone https://github.com/bytedance/deer-flow.git $DeerFlowRoot
}

$Required = @("Makefile", "backend", "frontend", "config.example.yaml")
foreach ($Item in $Required) {
    if (-not (Test-Path (Join-Path $DeerFlowRoot $Item))) {
        throw "DeerFlow root validation failed: missing $Item"
    }
}

if (-not (Get-Command make -ErrorAction SilentlyContinue)) {
    throw "The 'make' command is required by DeerFlow's official bootstrap. Install/enable Make, then re-run this script."
}

Push-Location $DeerFlowRoot
try {
    if (-not (Test-Path "config.yaml")) {
        Write-Host "Creating config.yaml with DeerFlow's repository command..."
        & make config
        if ($LASTEXITCODE -ne 0) { throw "make config failed" }
    } else {
        Write-Host "config.yaml already exists; leaving existing values unchanged."
    }

    $DockerReady = $false
    if (Get-Command docker -ErrorAction SilentlyContinue) {
        & docker info *> $null
        if ($LASTEXITCODE -eq 0) { $DockerReady = $true }
    }

    if ($DockerReady) {
        Write-Host "Docker daemon detected. Preparing DeerFlow Docker prerequisites..."
        & make docker-init
        if ($LASTEXITCODE -ne 0) { throw "make docker-init failed" }
        $SetupPath = "Docker"
        $NextCommand = "make docker-start"
    } else {
        Write-Host "Docker daemon unavailable. Checking local DeerFlow prerequisites..."
        & make check
        if ($LASTEXITCODE -ne 0) {
            throw "make check reported missing prerequisites. Install only the reported tools, then re-run this script."
        }
        & make install
        if ($LASTEXITCODE -ne 0) { throw "make install failed" }
        $SetupPath = "Local"
        $NextCommand = "make dev"
    }

    $SkillSource = Join-Path $OrderflowRoot "integrations\deerflow\skills\custom\orderflow-research"
    $SkillTarget = Join-Path $DeerFlowRoot "skills\custom\orderflow-research"
    if (-not (Test-Path $SkillSource)) {
        throw "Migration skill source is missing: $SkillSource"
    }

    if (Test-Path $SkillTarget) {
        if ($UpdateSkill) {
            Write-Host "Updating existing orderflow-research DeerFlow skill..."
            Remove-Item -Recurse -Force $SkillTarget
            Copy-Item -Recurse -Force $SkillSource $SkillTarget
        } else {
            Write-Host "orderflow-research skill already exists; preserving it. Use -UpdateSkill to replace it from the repo template."
        }
    } else {
        New-Item -ItemType Directory -Force (Split-Path -Parent $SkillTarget) | Out-Null
        Copy-Item -Recurse $SkillSource $SkillTarget
    }

    $Commit = "unknown"
    try {
        $Commit = (& git -C $OrderflowRoot rev-parse HEAD).Trim()
    } catch {}
    $LocalReference = @"
# Generated local project binding

This file is generated by `integrations/deerflow/bootstrap.ps1` and may be replaced on the next bootstrap.

- orderflow_project_root: `$OrderflowRoot`
- deerflow_project_root: `$DeerFlowRoot`
- orderflow_git_commit: `$Commit`
- generated_at_utc: `$([DateTime]::UtcNow.ToString("o"))`

Use `orderflow_project_root` as the canonical working directory for trading-project commands.
"@
    $ReferenceDir = Join-Path $SkillTarget "references"
    New-Item -ItemType Directory -Force $ReferenceDir | Out-Null
    Set-Content -Path (Join-Path $ReferenceDir "local-project.md") -Value $LocalReference -Encoding UTF8

    $ConfigText = Get-Content "config.yaml" -Raw
    $ReferencedEnvVars = [regex]::Matches($ConfigText, '\$([A-Z][A-Z0-9_]*)') |
        ForEach-Object { $_.Groups[1].Value } |
        Sort-Object -Unique

    $Lines = Get-Content "config.yaml"
    $ModelsStart = -1
    for ($i = 0; $i -lt $Lines.Count; $i++) {
        if ($Lines[$i] -match '^models:\s*$') { $ModelsStart = $i; break }
    }
    $ModelConfigured = $false
    if ($ModelsStart -ge 0) {
        for ($i = $ModelsStart + 1; $i -lt $Lines.Count; $i++) {
            if ($Lines[$i] -match '^[A-Za-z_][A-Za-z0-9_-]*:\s*') { break }
            if ($Lines[$i] -match '^\s{2}-\s+name:\s*\S+') { $ModelConfigured = $true; break }
        }
    }

    Write-Host ""
    Write-Host "DeerFlow bootstrap complete."
    Write-Host "Setup path: $SetupPath"
    Write-Host "config.yaml: present"
    Write-Host "orderflow-research skill: $SkillTarget"
    if (-not $ModelConfigured) {
        Write-Warning "No active model entry was detected under models: in config.yaml. Add at least one model before launch."
    }
    if ($ReferencedEnvVars.Count -gt 0) {
        Write-Host "Environment variable names referenced by config.yaml: $($ReferencedEnvVars -join ', ')"
        Write-Host "Values were not inspected."
    }
    Write-Host "Exact next command to launch DeerFlow:"
    Write-Host "  cd `"$DeerFlowRoot`""
    Write-Host "  $NextCommand"
} finally {
    Pop-Location
}
